parameters:
  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     symfony
  database_user:     root
  database_password: ~

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            whatever

  assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
  assetic.filter.compass.http_path:  /images

  app.data_dir: %kernel.root_dir%/../web/uploads/data
